Load

In [22]:
import pandas as pd
import numpy as np
import matplotlib as mt

In [23]:
DriversDF = pd.read_csv('drivers.csv')
RacesDF = pd.read_csv('races.csv')
ResultsDF = pd.read_csv('results.csv')

# Separate only the necessary from the data bases

## Get only the necessary from drivers.csv

In [24]:
DriversDF

,driverId,driverRef,number,code,forename,surname,dob,nationality,url
0,1,hamilton,44,HAM,Lewis,Hamilton,1985-01-07,British,http://en.wikipedia.org/wiki/Lewis_Hamilton
1,2,heidfeld,\N,HEI,Nick,Heidfeld,1977-05-10,German,http://en.wikipedia.org/wiki/Nick_Heidfeld
2,3,rosberg,6,ROS,Nico,Rosberg,1985-06-27,German,http://en.wikipedia.org/wiki/Nico_Rosberg
3,4,alonso,14,ALO,Fernando,Alonso,1981-07-29,Spanish,http://en.wikipedia.org/wiki/Fernando_Alonso
4,5,kovalainen,\N,KOV,Heikki,Kovalainen,1981-10-19,Finnish,http://en.wikipedia.org/wiki/Heikki_Kovalainen
...,...,...,...,...,...,...,...,...,...
856,858,sargeant,2,SAR,Logan,Sargeant,2000-12-31,American,http://en.wikipedia.org/wiki/Logan_Sargeant
857,859,lawson,30,LAW,Liam,Lawson,2002-02-11,New Zealander,http://en.wikipedia.org/wiki/Liam_Lawson
858,860,bearman,38,BEA,Oliver,Bearman,2005-05-08,British,http://en.wikipedia.org/wiki/Oliver_Bearman
859,861,colapinto,43,COL,Franco,Colapinto,2003-05-27,Argentinian,http://en.wikipedia.org/wiki/Franco_Colapinto
860,862,doohan,61,DOO,Jack,Doohan,2003-01-20,Australian,http://en.wikipedia.org/wiki/Jack_Doohan

In [25]:
Drivers = DriversDF[['driverId','forename','driverRef']]
Drivers

     driverId  forename   driverRef
0           1     Lewis    hamilton
1           2      Nick    heidfeld
2           3      Nico     rosberg
3           4  Fernando      alonso
4           5    Heikki  kovalainen
..        ...       ...         ...
856       858     Logan    sargeant
857       859      Liam      lawson
858       860    Oliver     bearman
859       861    Franco   colapinto
860       862      Jack      doohan

[861 rows x 3 columns]

## Get only the necessary from races.csv

In [ ]:
RacesDF

raceId          int64
year            int64
round           int64
circuitId       int64
name           object
date           object
time           object
url            object
fp1_date       object
fp1_time       object
fp2_date       object
fp2_time       object
fp3_date       object
fp3_time       object
quali_date     object
quali_time     object
sprint_date    object
sprint_time    object
dtype: object

In [27]:
Races = RacesDF[['raceId', 'circuitId', 'name', 'date', 'year']].sort_values(by='date', ascending = False)
Races1 = Races[(Races['raceId'] >= 1) & (Races['raceId'] <= 174)]
Races2 = Races[(Races['raceId'] >= 337) & (Races['raceId'] <= 355)]
Races3 = Races[(Races['raceId'] >= 841) & (Races['raceId'] <= 1124)]
RaceOrganizada = pd.concat([Races3, Races2, Races1])
RaceOrganizada

      raceId  circuitId                      name        date  year
1104    1124         22       Japanese Grand Prix  2024-04-07  2024
1103    1123          1     Australian Grand Prix  2024-03-24  2024
1102    1122         77  Saudi Arabian Grand Prix  2024-03-09  2024
1101    1121          3        Bahrain Grand Prix  2024-03-02  2024
1100    1120         24      Abu Dhabi Grand Prix  2023-11-26  2023
...      ...        ...                       ...         ...   ...
161      162          4        Spanish Grand Prix  2000-05-07  2000
160      161          9        British Grand Prix  2000-04-23  2000
159      160         21     San Marino Grand Prix  2000-04-09  2000
158      159         18      Brazilian Grand Prix  2000-03-26  2000
157      158          1     Australian Grand Prix  2000-03-12  2000

[459 rows x 5 columns]

In [39]:
RaceOrganizada
RaceOrganizadaCopy = RaceOrganizada
RaceOrganizadaCopy['raceId'] = RaceOrganizadaCopy['date']
RaceOrganizadaCopy

          raceId  circuitId                      name        date  year
1104  2024-04-07         22       Japanese Grand Prix  2024-04-07  2024
1103  2024-03-24          1     Australian Grand Prix  2024-03-24  2024
1102  2024-03-09         77  Saudi Arabian Grand Prix  2024-03-09  2024
1101  2024-03-02          3        Bahrain Grand Prix  2024-03-02  2024
1100  2023-11-26         24      Abu Dhabi Grand Prix  2023-11-26  2023
...          ...        ...                       ...         ...   ...
161   2000-05-07          4        Spanish Grand Prix  2000-05-07  2000
160   2000-04-23          9        British Grand Prix  2000-04-23  2000
159   2000-04-09         21     San Marino Grand Prix  2000-04-09  2000
158   2000-03-26         18      Brazilian Grand Prix  2000-03-26  2000
157   2000-03-12          1     Australian Grand Prix  2000-03-12  2000

[459 rows x 5 columns]

## Get only the necessary from results.csv

In [29]:
ResultsDF

,resultId,raceId,driverId,constructorId,number,grid,position,positionText,positionOrder,points,laps,time,milliseconds,fastestLap,rank,fastestLapTime,fastestLapSpeed,statusId
0,1,18,1,1,22,1,1,1,1,10.0,58,1:34:50.616,5690616,39,2,1:27.452,218.300,1
1,2,18,2,2,3,5,2,2,2,8.0,58,+5.478,5696094,41,3,1:27.739,217.586,1
2,3,18,3,3,7,7,3,3,3,6.0,58,+8.163,5698779,41,5,1:28.090,216.719,1
3,4,18,4,4,5,11,4,4,4,5.0,58,+17.181,5707797,58,7,1:28.603,215.464,1
4,5,18,5,1,23,3,5,5,5,4.0,58,+18.014,5708630,43,1,1:27.418,218.385,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26754,26760,1144,825,210,20,14,16,16,16,0.0,57,\N,\N,57,1,1:25.637,222.002,11
26755,26761,1144,859,215,30,12,17,17,17,0.0,55,\N,\N,52,12,1:28.751,214.212,5
26756,26762,1144,822,15,77,9,\N,R,18,0.0,30,\N,\N,14,19,1:29.482,212.462,130
26757,26763,1144,861,3,43,20,\N,R,19,0.0,26,\N,\N,5,17,1:29.411,212.631,5
26758,26764,1144,815,9,11,10,\N,R,20,0.0,0,\N,\N,\N,0,\N,\N,4

In [30]:
Results = ResultsDF[['raceId', 'driverId', 'position']]
Results.rename(columns={'raceId':'raceID'}, inplace= True)
Results

/tmp/ipykernel_2441/1769370448.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Results.rename(columns={'raceId':'raceID'}, inplace= True)

       raceID  driverId position
0          18         1        1
1          18         2        2
2          18         3        3
3          18         4        4
4          18         5        5
...       ...       ...      ...
26754    1144       825       16
26755    1144       859       17
26756    1144       822       \N
26757    1144       861       \N
26758    1144       815       \N

[26759 rows x 3 columns]

# Combine all of the information

In [36]:
All = pd.concat([Drivers, RaceOrganizada, Results], axis=1)
All = All.sort_values(by = 'year', ascending=False)

In [41]:
Allcopy = All.dropna()
Allcopy

,driverId,forename,driverRef,raceId,circuitId,name,date,year,raceID,driverId,position
859,861.0,Franco,colapinto,861.0,2.0,Malaysian Grand Prix,2012-03-25,2012.0,58,2,8
860,862.0,Jack,doohan,862.0,17.0,Chinese Grand Prix,2012-04-15,2012.0,58,17,9
858,860.0,Oliver,bearman,860.0,1.0,Australian Grand Prix,2012-03-18,2012.0,58,22,7
853,855.0,Guanyu,zhou,855.0,22.0,Japanese Grand Prix,2011-10-09,2011.0,58,30,2
852,854.0,Mick,mick_schumacher,854.0,15.0,Singapore Grand Prix,2011-09-25,2011.0,58,4,1
...,...,...,...,...,...,...,...,...,...,...,...
172,173.0,Elio,angelis,173.0,22.0,Japanese Grand Prix,2000-10-08,2000.0,26,5,5
161,162.0,Pierre-Henri,raphanel,162.0,4.0,Spanish Grand Prix,2000-05-07,2000.0,25,22,14
160,161.0,Volker,weidler,161.0,9.0,British Grand Prix,2000-04-23,2000.0,25,2,13
173,174.0,Johnny,dumfries,174.0,2.0,Malaysian Grand Prix,2000-10-22,2000.0,26,4,6
162,163.0,René,arnoux,163.0,20.0,European Grand Prix,2000-05-21,2000.0,25,6,15

In [32]:
Cate = {
    '18': 'Australian Grand Prix',
    '19': 'Malaysian Grand Prix',
    '20': 'Chinese Grand Prix'
}

All['Cate'] = All['raceID'].astype(str).map(Cate)

All[['raceID', 'Cate']]

       raceID                   Cate
0          18  Australian Grand Prix
1          18  Australian Grand Prix
2          18  Australian Grand Prix
3          18  Australian Grand Prix
4          18  Australian Grand Prix
...       ...                    ...
26754    1144                    NaN
26755    1144                    NaN
26756    1144                    NaN
26757    1144                    NaN
26758    1144                    NaN

[26759 rows x 2 columns]